# Whether 1.7 clients are supported.
legacy-support: true
tablist:
  update-ticks: 100
  columns: 4
# Header and footer now support multiple lines
# Use [] to disable, for example:
# header: []
header:
  - '&b&lStrikeTab &7&l- &3&lTablist Addon'
footer:
  - '&7Contact Toppe#4670 for StrikeTab'
# Used to sort players in tab
sort-ranks:
  admin:
    permission: 'strikepractice.admin'
    prefix: '&c'
  staff:
    permission: 'strikepractice.staff'
    prefix: '&d'
  donator:
    permission: 'strikepractice.donator'
    prefix: '&e'

slots:
  # You can use "ping=<number>" e.g "ping=10" to set the ping
  # Use "skin=<skin>" e.g "skin=Toppe5" to set the skin
  # Use "/striketab skins" to see all available skins.
  default:
    column-1:
      - ' '
      - '&7Online: &f%strikepractice_players%'
      - '&7Staff Online: &f%strikepractice_online_staff%'
      - ' '
      - ' '
      - '&6Global Elo: &7%strikepractice_global_elo%'
      - '&6NoDebuff: &7%strikepractice_elo_nodebuffelo%'
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
    column-2:
      - ' ' # First slot of the second column
      - '&7Ping: &f%strikepractice_ping% ms ping=%strikepractice_ping%'
      - '&7In Fights: &f%strikepractice_in_fight%'
      - ' '
      - '&b&lYour Stats skin=%strikepractice_player%'
      - '&6Kills: &7%strikepractice_kills%'
      - '&6Deaths: &7%strikepractice_deaths%'
      - '&6Elo Rank: &7%strikepractice_elo_rank%'
      - '&6Event wins: &7%strikepractice_event_wins%'
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
    column-3:
      - ' '
      - '&7Ranked Queue: &f%strikepractice_in_ranked_queue%'
      - '&7Unranked Queue: &f%strikepractice_in_unranked_queue%'
      - ' '
      - ' '
      - '&6Rankeds left: &7%strikepractice_rankeds_left%'
      - '&6Unrankeds left: &7%strikepractice_unrankeds_left%'
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
  in_match:
    column-1:
      - ' '
      - '&7Online: &f%strikepractice_players%'
      - ' '
      - '&a&lYou'
      - '%strikepractice_teammate_colored1% skin=%strikepractice_teammate1%'
      - '%strikepractice_teammate_colored2% skin=%strikepractice_teammate2%'
      - '%strikepractice_teammate_colored3% skin=%strikepractice_teammate3%'
      - '%strikepractice_teammate_colored4% skin=%strikepractice_teammate4%'
      - '%strikepractice_teammate_colored5% skin=%strikepractice_teammate5%'
      - '%strikepractice_teammate_colored6% skin=%strikepractice_teammate6%'
      - '%strikepractice_teammate_colored7% skin=%strikepractice_teammate7%'
      - '%strikepractice_teammate_colored8% skin=%strikepractice_teammate8%'
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
    column-2:
      - ' '
      - '&7Ping: &e%strikepractice_ping% ms ping=%strikepractice_ping%'
      - '&7Opponent &ePing: %strikepractice_opponent_ping% ms ping=%strikepractice_opponent_ping%'
      - '&6Kit: %strikepractice_kit%'
      - '&6Arena: %strikepractice_arena%'
      - '&6Opponent Elo: %strikepractice_opponent_elo% [display=%strikepractice_ranked%]'
      - '&6Round: %strikepractice_round%/%strikepractice_total_rounds% [display=%strikepractice_is_bestof%]'
      - '&6Wins: &a%strikepractice_own_wins% - %strikepractice_opponent_wins% [display=%strikepractice_is_bestof%]'
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
    column-3:
      - ' '
      - '&7Staff Online: &f%strikepractice_online_staff%'
      - ' '
      - '&c&lOpponent(s)'
      - '%strikepractice_opponent_colored1% skin=%strikepractice_opponent1%'
      - '%strikepractice_opponent_colored2% skin=%strikepractice_opponent2%'
      - '%strikepractice_opponent_colored3% skin=%strikepractice_opponent3%'
      - '%strikepractice_opponent_colored4% skin=%strikepractice_opponent4%'
      - '%strikepractice_opponent_colored5% skin=%strikepractice_opponent5%'
      - '%strikepractice_opponent_colored6% skin=%strikepractice_opponent6%'
      - '%strikepractice_opponent_colored7% skin=%strikepractice_opponent7%'
      - '%strikepractice_opponent_colored8% skin=%strikepractice_opponent8%'
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '